// <auto-generated />
using System;
using CafeMVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CafeMVC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CafeMVC.Models.CafeChain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CuisineType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("FoundedYear")
                        .HasColumnType("integer");

                    b.Property<string>("Menu")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Regions")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.ToTable("CafeChains");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CuisineType = "Фастфуд",
                            FoundedYear = 2022,
                            Menu = "Бургеры, картофель фри",
                            Name = "Вкусно и точка",
                            Regions = "Москва, Санкт-Петербург"
                        },
                        new
                        {
                            Id = 2,
                            CuisineType = "Русская",
                            FoundedYear = 1998,
                            Menu = "Блины, каши, супы",
                            Name = "Теремок",
                            Regions = "Москва"
                        },
                        new
                        {
                            Id = 3,
                            CuisineType = "Японская",
                            FoundedYear = 2003,
                            Menu = "Суши, роллы, рамен",
                            Name = "Якитория",
                            Regions = "Москва, Екатеринбург"
                        });
                });

            modelBuilder.Entity("CafeMVC.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CafeChainId")
                        .HasColumnType("integer");

                    b.Property<string>("Dishes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("OrderTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CafeChainId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CafeChainId = 1,
                            Dishes = "Бургер классический, Кола",
                            OrderNumber = "ORD-001",
                            OrderTime = new DateTime(2025, 1, 15, 12, 30, 0, 0, DateTimeKind.Utc),
                            Status = "Выполнен"
                        },
                        new
                        {
                            Id = 2,
                            CafeChainId = 2,
                            Dishes = "Блин с мясом, Чай",
                            OrderNumber = "ORD-002",
                            OrderTime = new DateTime(2025, 1, 16, 14, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Готовится"
                        });
                });

            modelBuilder.Entity("CafeMVC.Models.Order", b =>
                {
                    b.HasOne("CafeMVC.Models.CafeChain", "CafeChain")
                        .WithMany("Orders")
                        .HasForeignKey("CafeChainId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CafeChain");
                });

            modelBuilder.Entity("CafeMVC.Models.CafeChain", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
